create table if not exists public.daily_intel_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  stock_hot jsonb,
  stock_cold jsonb,
  crypto_hot jsonb,
  crypto_cold jsonb,
  created_at timestamptz not null default now()
);

-- needed for on_conflict=report_date
create unique index if not exists daily_intel_reports_report_date_key
  on public.daily_intel_reports (report_date);
